CREATE TABLE LOGIN (
  correo VARCHAR(80) NOT NULL,
  contraseña VARCHAR(255) NOT NULL,
  ultimaConexion DATETIME NOT NULL,
  estado TINYINT(1) NOT NULL,
  PRIMARY KEY(correo)
);

CREATE TABLE DEPARTAMENTO (
  idDepartamento INTEGER NOT NULL,
  nombreDepartamento VARCHAR(80) NOT NULL,
  PRIMARY KEY(idDepartamento)
);

CREATE TABLE ROL (
  idRol INTEGER NOT NULL AUTO_INCREMENT,
  nombreRol VARCHAR(30) NOT NULL,
  estadoRol TINYINT(1) NOT NULL,
  PRIMARY KEY(idRol)
);

CREATE TABLE MARCA (
  idMarca INTEGER NOT NULL,
  nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY(idMarca)
);

CREATE TABLE TARIFA (
  idTarifa INTEGER NOT NULL AUTO_INCREMENT,
  porHora FLOAT NOT NULL,
  porDia FLOAT NOT NULL,
  PRIMARY KEY(idTarifa)
);

CREATE TABLE DATAMASTER (
  idDataMaster INTEGER NOT NULL AUTO_INCREMENT,
  nombreDataMaster VARCHAR(30) NOT NULL,
  descripcionDataMaster VARCHAR(80) NOT NULL,
  PRIMARY KEY(idDataMaster)
);

CREATE TABLE CIUDAD (
  idCiudad INTEGER NOT NULL,
  idDepartamento INTEGER NOT NULL,
  nombreCiudad VARCHAR(100) NOT NULL,
  PRIMARY KEY(idCiudad),
  FOREIGN KEY(idDepartamento)
    REFERENCES DEPARTAMENTO(idDepartamento)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE MODELO (
  idModelo INTEGER NOT NULL,
  idMarca INTEGER NOT NULL,
  nombre VARCHAR(50) NULL,
  PRIMARY KEY(idModelo),
  FOREIGN KEY(idMarca)
    REFERENCES MARCA(idMarca)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE DATATYPE (
  idDataType INTEGER NOT NULL AUTO_INCREMENT,
  idDataMaster INTEGER NOT NULL,
  nombreDataType VARCHAR(30) NOT NULL,
  descripcionDataType VARCHAR(100) NOT NULL,
  PRIMARY KEY(idDataType),
  FOREIGN KEY(idDataMaster)
    REFERENCES DATAMASTER(idDataMaster)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE USUARIO (
  idUsuario INTEGER NOT NULL AUTO_INCREMENT,
  idCiudad INTEGER NOT NULL,
  idTipoDocumento INTEGER NOT NULL,
  idSexo INTEGER NOT NULL,
  idRol INTEGER NOT NULL,
  correo VARCHAR(80) NOT NULL,
  DNI VARCHAR(11) UNIQUE NOT NULL ,
  nombre VARCHAR(80) NOT NULL,
  apellido VARCHAR(80) NOT NULL,
  telefono VARCHAR(10) NOT NULL,
  fechaNacimiento DATE NOT NULL,
  rutaFoto VARCHAR(200) NOT NULL,
  PRIMARY KEY(idUsuario),
  FOREIGN KEY(correo)
    REFERENCES LOGIN(correo)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idRol)
    REFERENCES ROL(idRol)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idSexo)
    REFERENCES DATATYPE(idDataType)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idTipoDocumento)
    REFERENCES DATATYPE(idDataType)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idCiudad)
    REFERENCES CIUDAD(idCiudad)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE VEHICULO (
  idVehiculo INTEGER NOT NULL AUTO_INCREMENT,
  idTipoVehiculo INTEGER NOT NULL,
  idTarifa INTEGER NOT NULL,
  idUsuario INTEGER NOT NULL,
  idTransmision INTEGER NOT NULL,
  idCombustible INTEGER NOT NULL,
  idModelo INTEGER NOT NULL,
  placa VARCHAR(7) UNIQUE NOT NULL,
  año YEAR NOT NULL,
  Km INTEGER NOT NULL,
  isPlacaPar TINYINT(1) NOT NULL,
  PRIMARY KEY(idVehiculo),
  FOREIGN KEY(idModelo)
    REFERENCES MODELO(idModelo)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idCombustible)
    REFERENCES DATATYPE(idDataType)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idTransmision)
    REFERENCES DATATYPE(idDataType)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idUsuario)
    REFERENCES USUARIO(idUsuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idTarifa)
    REFERENCES TARIFA(idTarifa)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idTipoVehiculo)
    REFERENCES DATATYPE(idDataType)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE FOTOS (
  idFoto INTEGER NOT NULL AUTO_INCREMENT,
  idVehiculo INTEGER NOT NULL,
  ruta VARCHAR(200) NOT NULL,
  fechaCarga DATETIME NOT NULL,
  PRIMARY KEY(idFoto),
  FOREIGN KEY(idVehiculo)
    REFERENCES VEHICULO(idVehiculo)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE REPORTES (
  idUsuarioReporta INTEGER NOT NULL,
  dUsuarioReportado INTEGER NOT NULL,
  Causa VARCHAR(1000) NOT NULL,
  fechaReporte DATETIME NOT NULL,
  estado TINYINT(1) NOT NULL,
  PRIMARY KEY(idUsuarioReporta, dUsuarioReportado),
  FOREIGN KEY(idUsuarioReporta)
    REFERENCES USUARIO(idUsuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(dUsuarioReportado)
    REFERENCES USUARIO(idUsuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE RELACIONES (
  idUsuarioOcupante INTEGER NOT NULL,
  idUsuarioPropietario INTEGER NOT NULL,
  fechaRelacion DATE NOT NULL,
  PRIMARY KEY(idUsuarioOcupante, idUsuarioPropietario),
  FOREIGN KEY(idUsuarioOcupante)
    REFERENCES USUARIO(idUsuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idUsuarioPropietario)
    REFERENCES USUARIO(idUsuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE COMENTARIO (
  idComentario INTEGER NOT NULL AUTO_INCREMENT,
  dUsuario INTEGER NOT NULL,
  idVehiculo INTEGER NOT NULL,
  comentario VARCHAR(700) NOT NULL,
  calificacion FLOAT NOT NULL,
  fechaComentario DATETIME NOT NULL,
  PRIMARY KEY(idComentario),
  FOREIGN KEY(dUsuario)
    REFERENCES USUARIO(idUsuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idVehiculo)
    REFERENCES VEHICULO(idVEHICULO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE MENSAJES (
  idUsuarioRecibe INTEGER NOT NULL,
  idUsuarioEnvia INTEGER NOT NULL,
  fechaEnvia DATETIME NOT NULL,
  mensaje VARCHAR(5000) NOT NULL,
  estado TINYINT(1) NOT NULL,
  PRIMARY KEY(idUsuarioRecibe, idUsuarioEnvia),
  FOREIGN KEY(idUsuarioRecibe)
    REFERENCES USUARIO(idUsuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idUsuarioEnvia)
    REFERENCES USUARIO(idUsuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PUBLICACION (
  idPublicacion INTEGER NOT NULL AUTO_INCREMENT,
  idTipoPublicacion INTEGER NOT NULL,
  idUsuario INTEGER NOT NULL,
  publicacion VARCHAR(1000) NOT NULL,
  fechaInicio DATETIME NOT NULL,
  fechaFin DATETIME NOT NULL,
  fechaPublicacion DATETIME NOT NULL,
  PRIMARY KEY(idPublicacion),
  FOREIGN KEY(idUsuario)
    REFERENCES USUARIO(idUsuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idTipoPublicacion)
    REFERENCES DATATYPE(idDataType)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE CONTRATO (
  idPropietario INTEGER NOT NULL,
  idOcupante INTEGER NOT NULL,
  VEHICULO_idVehiculo INTEGER NOT NULL,
  fechaInicio DATETIME NOT NULL,
  fechaFin DATETIME NOT NULL,
  valor FLOAT NOT NULL,
  PRIMARY KEY(idPropietario, idOcupante),
  FOREIGN KEY(idOcupante)
    REFERENCES USUARIO(idUsuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idPropietario)
    REFERENCES USUARIO(idUsuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(VEHICULO_idVehiculo)
    REFERENCES VEHICULO(idVehiculo)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE SOLICITUD (
  idSolicitud INTEGER NOT NULL AUTO_INCREMENT,
  idUsuario INTEGER NOT NULL,
  idPublicacion INTEGER NOT NULL,
  fechaSolicitud DATETIME NOT NULL,
  PRIMARY KEY(idSolicitud),
  FOREIGN KEY(idPublicacion)
    REFERENCES PUBLICACION(idPublicacion)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idUsuario)
    REFERENCES USUARIO(idUsuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

